CREATE TABLE `accounts` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(20) NOT NULL UNIQUE,
	`password` VARCHAR(30) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`country` VARCHAR(4) NOT NULL,
	`session` INT NULL DEFAULT '0'
) DEFAULT CHARSET=latin1;